// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/metObs/": {
            "get": {
                "description": "Get metrological observations for a given date. If no date is given, the current date is used.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metObs"
                ],
                "summary": "Get metrological observations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date (default: today)",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of years back to get observations for (default: 10)",
                        "name": "numberOfYears",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MetObservationResponse"
                        }
                    }
                }
            }
        },
        "/oceanObs/": {
            "get": {
                "description": "Get the current ocean temperature and highest temperature in the past 24h from a fixed set of locations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oceanObs"
                ],
                "summary": "Get current ocean temperature",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OceanObservationsResponse"
                        }
                    }
                }
            }
        },
        "/oceanObs/{stationId}": {
            "get": {
                "description": "Get the current ocean temperature and highest temperature in the past 24h from a specific location",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oceanObs"
                ],
                "summary": "Get current ocean temperature from a specific location",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Station ID",
                        "name": "stationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OceanObservationResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.MetObservationResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "maxAverage": {
                    "type": "number"
                },
                "minAverage": {
                    "type": "number"
                },
                "temperatureObservations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TemperatureObservation"
                    }
                }
            }
        },
        "models.OceanObservation": {
            "type": "object",
            "properties": {
                "latestTemperature": {
                    "type": "number"
                },
                "maxTemp24H": {
                    "type": "number"
                },
                "stationId": {
                    "type": "integer"
                },
                "stationName": {
                    "type": "string"
                }
            }
        },
        "models.OceanObservationResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "observation": {
                    "$ref": "#/definitions/models.OceanObservation"
                }
            }
        },
        "models.OceanObservationsResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "observations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OceanObservation"
                    }
                }
            }
        },
        "models.TemperatureObservation": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
