definitions:
  models.MetObservationResponse:
    properties:
      date:
        type: string
      maxAverage:
        type: number
      minAverage:
        type: number
      temperatureObservations:
        items:
          $ref: '#/definitions/models.TemperatureObservation'
        type: array
    type: object
  models.OceanObservation:
    properties:
      latestTemperature:
        type: number
      maxTemp24H:
        type: number
      stationId:
        type: integer
      stationName:
        type: string
    type: object
  models.OceanObservationResponse:
    properties:
      date:
        type: string
      observation:
        $ref: '#/definitions/models.OceanObservation'
    type: object
  models.OceanObservationsResponse:
    properties:
      date:
        type: string
      observations:
        items:
          $ref: '#/definitions/models.OceanObservation'
        type: array
    type: object
  models.TemperatureObservation:
    properties:
      max:
        type: number
      min:
        type: number
      year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /metObs/:
    get:
      description: Get metrological observations for a given date. If no date is given,
        the current date is used.
      parameters:
      - description: 'Date (default: today)'
        in: query
        name: date
        type: string
      - description: 'Number of years back to get observations for (default: 10)'
        in: query
        name: numberOfYears
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MetObservationResponse'
      summary: Get metrological observations
      tags:
      - metObs
  /oceanObs/:
    get:
      description: Get the current ocean temperature and highest temperature in the
        past 24h from a fixed set of locations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OceanObservationsResponse'
      summary: Get current ocean temperature
      tags:
      - oceanObs
  /oceanObs/{stationId}:
    get:
      description: Get the current ocean temperature and highest temperature in the
        past 24h from a specific location
      parameters:
      - description: Station ID
        in: path
        name: stationId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OceanObservationResponse'
      summary: Get current ocean temperature from a specific location
      tags:
      - oceanObs
swagger: "2.0"
