definitions:
  models.MetObservationResponse:
    properties:
      date:
        type: string
      maxAverage:
        type: number
      minAverage:
        type: number
      temperatureObservations:
        items:
          $ref: '#/definitions/models.TemperatureObservation'
        type: array
    type: object
  models.OceanObservation:
    properties:
      latestTemperature:
        type: number
      maxTemp24H:
        type: number
      stationId:
        type: integer
      stationName:
        type: string
    type: object
  models.OceanObservationResponse:
    properties:
      date:
        type: string
      observations:
        items:
          $ref: '#/definitions/models.OceanObservation'
        type: array
    type: object
  models.TemperatureObservation:
    properties:
      max:
        type: number
      min:
        type: number
      year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /metObs/:
    get:
      description: Get metrological observations for a given date
      parameters:
      - description: Date
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MetObservationResponse'
      summary: Get metrological observations
      tags:
      - metObs
  /oceanObs/:
    get:
      description: Get the current ocean temperature and highest temperature in the
        past 24h from a fixed set of locations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OceanObservationResponse'
      summary: Get current ocean temperature
      tags:
      - oceanObs
swagger: "2.0"
