name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - "main"

jobs:

  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
