name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - "main"

jobs:

  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - run: 'echo ${{ secrets.GCP_SA_KEY }}'
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.TEST_SECRET }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'hello-cloud-run'
        metadata: app.yaml

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
