name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update DMI_MET_OBS_API_KEY in config.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "pkg/common/envs/config.yaml"
          propertyPath: "DMI_MET_OBS_API_KEY"
          value: ${{ secrets.DMI_MET_OBS_API_KEY }}
          commitChange: false
      - name: Update DMI_OCEAN_OBS_API_KEY in config.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "pkg/common/envs/config.yaml"
          propertyPath: "DMI_OCEAN_OBS_API_KEY"
          value: ${{ secrets.DMI_OCEAN_OBS_API_KEY }}
          commitChange: false
      - name: Update REDIS_DB_PSWD in config.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "pkg/common/envs/config.yaml"
          propertyPath: "REDIS_DB_PSWD"
          value: ${{ secrets.REDIS_DB_PSWD }}
          commitChange: false
      - name: Update REDIS_URL in config.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "pkg/common/envs/config.yaml"
          propertyPath: "REDIS_URL"
          value: ${{ secrets.REDIS_URL }}
          commitChange: false
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        with:
          project_id: kalles-weather-dashboard-api

      - name: "Check health"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
